
version: '3' #versión actual de la sintaxix

services: #contenedores (BASES DE DATOS POR SERVICIO):
  invoices_db_detail: #Nombre del servicio
    container_name: invoices_db_detail #Nombre contenedor
    image: postgres:latest #imagen a usar
    restart: unless-stopped #criterio de detención
    environment: #variables de entorno
      POSTGRES_DB: detail
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
    ports: #puertos a exponer
      - "5434:5434"
    expose:
      - 5434
    command: -p 5434
  invoices_db_document:
    container_name: invoices_db_document
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: document
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
    ports:
      - "5435:5435"
    expose:
      - 5435
    command: -p 5435
  invoices_db_provider:
    container_name: invoices_db_provider
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: provider
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
    ports:
      - "54346:5436"
    expose:
      - 5436
    command: -p 5436
  invoices_db_receiver:
    container_name: invoices_db_receiver
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: receiver
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
    ports:
      - "5437:5437"
    expose:
      - 5437
    command: -p 5437
  invoices_db_mail-supplier:
    container_name: invoices_db_mail-supplier
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: mail-supplier
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
    ports:
      - "5438:5438"
    expose:
      - 5438
    command: -p 5438